#!/bin/bash
#SBATCH -p main
#SBATCH --job-name=fastqc_job
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=24G
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

# Charger le module nécessaire
module load FastQC/0.11.9

# Créer le répertoire de travail sur /scratch
mkdir -p /scratch/$USER/FASTQC

# Lancer l'analyse avec fastqc
find /projects/large/CIBIG_rice/01.RawData/C/ -type f -name "*fq.gz" -exec fastqc {} -o /scratch/$USER/FASTQC \;

# Copier les résultats dans le répertoire personnel sur le master
cp -r /scratch/$USER/FASTQC /home/$USER/Resultats/

# Supprimer le répertoire de travail pour libérer de l'espace
rm -rf /scratch/$USER/FASTQC
